name: Publish Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Publish
      run: dotnet publish Panopticon.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish
    - name: Zip Release
      run: Compress-Archive -Path ./publish/* -DestinationPath Panopticon-${{ github.ref_name }}-win-x64.zip
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: Panopticon-${{ github.ref_name }}-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}