name: Publish Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Publish
      run: dotnet publish Panopticon.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish
    - name: Zip Release
      run: Compress-Archive -Path ./publish/* -DestinationPath Panopticon-${{ github.ref_name }}-win-x64.zip
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: Panopticon-${{ github.ref_name }}-win-x64.zip
        body: |
          Panopticon ${{ github.ref_name }}
          - Beta release.
          - Self-contained Windows x64 executable.
          - Changelog: 
            + Added new TimeTravel option: New Game            
            + Added migration procedure logic.
            + Undoing a node will now delete its associated note.
            + Existing notes are now carrying over when braching off.
            + panopticon.db & .gitignore are now only created when a Timeline is created by the user.
            + Most buttons "BackColor" are now black.
          - Features: Snapshot creation, Undo, Replay mode, Branch off, New Game, Switch branch, Save notes.
          - Missing Features: Note templates, keyboard shortcut and proper TAB cycling.
          - SHA256 hash of Panopticon.exe:
            4c0fa782f921a95114f120bc1012485190c028646cdb286a05a5d1d67ba90bff
            CertUtil: -hashfile command completed successfully.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}